print('a\tb\tc\td\n')
print('H   H  EEEEE  L      L     OOOOOO')
print('H   H  E      L      L     O    O')
print('H   H  E      L      L     O    O')
print('HHHHH  EEEEE  L      L     O    O')
print('H   H  E      L      L     O    O')
print('H   H  E      L      L     O    O')
print('H   H  EEEEE  LLLLL  LLLLL OOOOOO\n')
print(4*1)
print(4*2)
print(4*3)
print(4*4)
